### ISSUE TITLE
Codepen error - "codepen.io refused to connect."

### ISSUE THREAD

**Issue by huukimit** [leedo/noembed#106]
I tried to get iframe HTML with Codepen. The "codepen.io refused to connect" error is shown. It seems due to Codepen has been implemented Captcha for all request to codepen.io. :-? Therefore, we saw this error. Should we implement Codepen in the other way: Prefill embed or HTML?

**Comment by huukimit** [comment]
Codepen adjusted their Cloudflare configs then the issue is resolved.

**Comment by ridbay** [comment]
I am presently getting this same issue with all the websites I visit that have codepen embedded.
What could be the issue?

**Comment by whiteSnow0213** [comment]
Sometimes it is the same problem for me. Net work problem?

**Comment by elise01** [comment]
I am getting the same problem using CodePen. Unable to access google.com and adafruit.com/educators. I haven't tried other websites yet. Websites refuse to connect. Any ideas how to get past this please?

**Comment by shinriyo** [comment]
JSFiddle

**Comment by Oishik91** [comment]
// Firebase Configuration
const firebaseConfig = {
    apiKey: "YOUR_API_KEY",
    authDomain: "YOUR_AUTH_DOMAIN",
    databaseURL: "YOUR_DATABASE_URL",
    projectId: "YOUR_PROJECT_ID",
    storageBucket: "YOUR_STORAGE_BUCKET",
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    appId: "YOUR_APP_ID"
};
firebase.initializeApp(firebaseConfig);
const db = firebase.database();

const chatBox = document.getElementById("chat-box");
const messageInput = document.getElementById("message-input");

// Load Messages
db.ref("messages").on("child_added", (snapshot) => {
    const message = snapshot.val();
    const messageElement = document.createElement("div");
    messageElement.textContent = message;
    chatBox.appendChild(messageElement);
    chatBox.scrollTop = chatBox.scrollHeight;
});

// Send Message
function sendMessage() {
    const message = messageInput.value;
    if (message.trim() !== "") {
        db.ref("messages").push(message);
        messageInput.value = "";
    }
}

// Logout and Clear Messages
function logout() {
    db.ref("messages").remove() // Remove all messages
        .then(() => {
            alert("সব মেসেজ মুছে ফেলা হয়েছে!");
            window.location.reload(); // Reload to clear chat box
        });
}

**Comment by Oishik91** [comment]
// Firebase Configuration
const firebaseConfig = {
    apiKey: "YOUR_API_KEY",
    authDomain: "YOUR_AUTH_DOMAIN",
    databaseURL: "YOUR_DATABASE_URL",
    projectId: "YOUR_PROJECT_ID",
    storageBucket: "YOUR_STORAGE_BUCKET",
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    appId: "YOUR_APP_ID"
};
firebase.initializeApp(firebaseConfig);
const db = firebase.database();

const chatBox = document.getElementById("chat-box");
const messageInput = document.getElementById("message-input");

// Load Messages
db.ref("messages").on("child_added", (snapshot) => {
    const message = snapshot.val();
    const messageElement = document.createElement("div");
    messageElement.textContent = message;
    chatBox.appendChild(messageElement);
    chatBox.scrollTop = chatBox.scrollHeight;
});

// Send Message
function sendMessage() {
    const message = messageInput.value;
    if (message.trim() !== "") {
        db.ref("messages").push(message);
        messageInput.value = "";
    }
}

// Logout and Clear Messages
function logout() {
    db.ref("messages").remove() // Remove all messages
        .then(() => {
            alert("সব মেসেজ মুছে ফেলা হয়েছে!");
            window.location.reload(); // Reload to clear chat box
        });
}

**Comment by Oishik91** [comment]
#chat-container {
    width: 300px;
    margin: auto;
    text-align: center;
}

#chat-box {
    border: 1px solid #ccc;
    height: 300px;
    overflow-y: auto;
    margin-bottom: 10px;
}

#message-input {
    width: 80%;
}

**Comment by Oishik91** [comment]
![Uploading IMG_20241030_152032.jpg…]()
