### ISSUE TITLE
SSL Certificate Invalid

### ISSUE THREAD

**Issue by TonyDjent** [leedo/noembed#123]
I believe the SSL certificate for noembed.com has an issue and will cause many fetch errors.

**Comment by danechitoaie** [comment]
Same problem. Noticed few hours ago.

**Comment by TonyDjent** [comment]
This SSL certificate appears to be valid again, and working properly, closing this issue.

**Comment by yougotwill** [comment]
Not sure if this is the same issue so opened a new one https://github.com/leedo/noembed/issues/125
