### ISSUE TITLE
Documentation for running locally

### ISSUE THREAD

**Issue by tomgross** [leedo/noembed#53]
To implement a new video provider (https://tube.switch.ch/) I am trying to run noembed locally. After installing al requested packages I get the following error when running locally:
```
$ plackup app.psgi
Error while loading /home/vagrant/noembed/eg/app.psgi: Can't locate object method "new" via package "AnyEvent::Fork" at ../lib/Noembed/Util.pm line 12.
```

Is there any documentation how to run this locally or a troubleshooting guide?

**Comment by leedo** [comment]
Sorry about that! You'll need to install quite a few dependencies. For that I recommend using `cpanm` (cpanminus). You can run `cpanm --installdeps` inside the git directory to get everything installed. Hope that helps!

**Comment by tomgross** [comment]
@leedo Thanks for your help. Unfortunately this does not help. What I have is Fedora 21, Perl v5.18.4
Installing all dependencies seems to work. I do:

```
$ cpanm --installdeps .
$ perl Makefile.PL
$ make
$ cd eg
$ plackup app.psgi
```
The error mentioned above stays the same.

**Comment by leedo** [comment]
You don't actually need to run the Makefile if you plan to run it out of the source directory. After installing the dependencies, you should be able to run the app with:

<pre>
cd eg
plackup -I../lib app.psgi
</pre>

**Comment by tomgross** [comment]
Needed this https://github.com/leedo/noembed/pull/54 to make it work. Thanks for your help and now we have a documentation too :wink:
