### ISSUE TITLE
TED support broken?

### ISSUE THREAD

**Issue by jdieckmannelm** [leedo/noembed#55]
Hi everyone,

the noembed TED service seems to behave a little bit different when compared to the native oembed service TED is offering, in terms of:
- The native oembed service accepts http and https URLs. The noembed service only accepts http URLs.
- The native oembed service accepts URLs with and without the ".html" suffix. The noembed service only accepts URLs with the ".html" suffix.
- The native oembed service returns the expected (at least for me) type "video". The noembed service returns type "richt".

Not relevant to me, but i noticed:
- The native oembed service returns a full set of properties (author_name,author_url,description,height,html,provider_name,provider_url,thumbnail_height,thumbnail_url,thumbnail_width,title,type,url,version,width). The noembed service returns only a few of them (html,provider_name,title,type,url).

My question is, do you agree with my list or is this behavior by design? I would like our users to put in whatever URL they see in the browsers address bar, but unfortunately that are primarily https URLs without the ".html" suffix :-/.

As i am not familiar with perl a cannot participate directly in changing anything mentioned above but would like to help wherever i can.

I would be grateful for any feedback.
Thank you!

**Comment by leedo** [comment]
This has been fixed. Thanks!
