### ISSUE TITLE
How is the site free?

### ISSUE THREAD

**Issue by faceleg** [leedo/noembed#61]
This looks like an awesome project and will help me save time - all I need is title and thumbnails for youtube and vimeo, being able to get these without bothering with api keys etc is a lifesaver.

It all sounds too good to be true - how is it free? I would have thought such a great service would have generated significant traffic, hosting costs etc?

**Comment by leedo** [comment]
It was previously paid for by proceeds from another small web service. It has since been put behind Fastly for free, and runs on a fairly small EC2 instance. It does about 50-100 req/sec currently.
