### ISSUE TITLE
static references to noembed.com

### ISSUE THREAD

**Issue by nicopace** [leedo/noembed#66]
hi!
I found out that there are many static references to noembed.com
https://github.com/leedo/noembed/search?utf8=%E2%9C%93&q=%22noembed.com%22&type=Code
Would be great to not have them, in order for each instance to be completely independant of the home page.

**Comment by nicopace** [comment]
We should correct these ones:
  * https://github.com/leedo/noembed/blob/master/share/templates/wrapper.html
  * https://github.com/leedo/noembed/blob/master/lib/Noembed/Provider.pm
  * https://github.com/leedo/noembed/blob/master/lib/Noembed/ImageProvider.pm

**Comment by leedo** [comment]
Agreed. I recently did a bit of a rewrite which simplifies things a lot, and adds a config file for this stuff. I will push it soon. Thanks!
